"""
Django settings for smrcwebpage project.

Generated by 'django-admin startproject' using Django 5.2.5.

Docs:
- https://docs.djangoproject.com/en/5.2/topics/settings/
- https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env values for local/dev or docker
load_dotenv()

# -------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------------------------------------------------
# Security / core config
# -------------------------------------------------------------------

# SECRET_KEY:
# In prod this comes from env (GitHub env secret / container env).
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "CHANGE_ME_IN_PRODUCTION"  # fallback so local doesn't crash
)

# DEBUG:
# Controlled by env. DEBUG must be False in prod.
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

# ALLOWED_HOSTS:
# Comma-separated in env. Default covers your prod + dev.
ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "srmc.com.ph,localhost,127.0.0.1,10.10.90.6"
).split(",")

# CSRF trusted origins:
# Must include scheme (http/https) and port for non-80/443.
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://srmc.com.ph",
    "http://10.10.90.6",
    "https://10.10.90.6",
]

# If you're behind a reverse proxy that terminates TLS (nginx/ingress),
# you'll likely also need in production:
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# SECURE_SSL_REDIRECT = not DEBUG


# -------------------------------------------------------------------
# Applications
# -------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # WhiteNoise must be right after SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smrcwebpage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # If you add a global templates/ dir, put BASE_DIR / "templates" here
        'DIRS': [],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smrcwebpage.wsgi.application'


# -------------------------------------------------------------------
# Database
# -------------------------------------------------------------------
# Local dev default: sqlite
# CI/prod: override with env to use Postgres

DEFAULT_SQLITE_PATH = BASE_DIR / 'db.sqlite3'

DB_ENGINE = os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3')
DB_NAME = os.environ.get('DB_NAME', DEFAULT_SQLITE_PATH)
DB_USER = os.environ.get('DB_USER', '')
DB_PASSWORD = os.environ.get('DB_PASSWORD', '')
DB_HOST = os.environ.get('DB_HOST', '')
DB_PORT = os.environ.get('DB_PORT', '')

DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}

# NOTE:
# For CI we export:
#   DB_ENGINE=django.db.backends.postgresql
#   DB_NAME=test_db
#   DB_USER=postgres
#   DB_PASSWORD=postgres
#   DB_HOST=localhost
#   DB_PORT=5432
#
# In prod you'll point these to your real Postgres.
# Make sure `psycopg2-binary` is in requirements.txt so Django can talk to Postgres.


# -------------------------------------------------------------------
# Password validation
# -------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# -------------------------------------------------------------------
# Internationalization / Time
# -------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'

# Match deploy region (Philippines)
TIME_ZONE = 'Asia/Manila'

USE_I18N = True

# Keep True so Django stores tz-aware datetimes (UTC in DB)
USE_TZ = True


# -------------------------------------------------------------------
# Static files
# -------------------------------------------------------------------

# URL for static files
STATIC_URL = "/static/"

# During dev: where your app-level static assets live
STATICFILES_DIRS = [BASE_DIR / "assets"]

# During collectstatic: final location for production serving
STATIC_ROOT = BASE_DIR / "staticfiles"

# Tell WhiteNoise to serve compressed, hashed files in prod
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# -------------------------------------------------------------------
# Default primary key type
# -------------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# -------------------------------------------------------------------
# Email / SMTP
# -------------------------------------------------------------------

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = True  # STARTTLS on port 587 (Gmail style)

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'admin0108@gmail.com')

# Never commit the real password. Use env / GitHub environment secret.
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER or 'webmaster@localhost'
)
