"""
Django settings for smrcwebpage project.

Generated by 'django-admin startproject' using Django 5.2.5.

Docs:
- https://docs.djangoproject.com/en/5.2/topics/settings/
- https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env (only really used in local/dev or docker)
load_dotenv()

# -------------------------------------------------------------------
# Paths
# -------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------------------------------------------------
# Security / core config
# -------------------------------------------------------------------

# SECRET_KEY:
# In production this MUST be provided via env (e.g. GitHub Actions env secret,
# container env, etc.). Never commit a real key here.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "CHANGE_ME_IN_PRODUCTION"  # fallback so local dev doesn't crash
)

# DEBUG:
# Do NOT leave this True in prod. Control it via env.
# e.g. DEBUG=False in your prod environment.
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

# ALLOWED_HOSTS:
# Comma-separated in env, example:
# ALLOWED_HOSTS="srmc.com.ph,localhost,127.0.0.1,10.10.90.6"
ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "srmc.com.ph,localhost,127.0.0.1,10.10.90.6"
).split(",")

# CSRF trusted origins:
# These must include scheme (http/https) and port if not default.
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    # prod / internal
    "https://srmc.com.ph",
    "http://10.10.90.6",
    "https://10.10.90.6",
]

# If you're behind a reverse proxy/ingress that terminates TLS (nginx, etc.),
# you may also eventually need:
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# SECURE_SSL_REDIRECT = not DEBUG


# -------------------------------------------------------------------
# Applications
# -------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # WhiteNoise should stay right after SecurityMiddleware so it can serve
    # collected static files in production.
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    # CSRF middleware must run for forms / POST protection
    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smrcwebpage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # If you have a custom templates/ dir at project root, add it here:
        # BASE_DIR / "templates"
        'DIRS': [],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smrcwebpage.wsgi.application'


# -------------------------------------------------------------------
# Database
# -------------------------------------------------------------------
# For prod you'll probably switch to Postgres, pulled from env.
# SQLite is fine for local/dev.

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', ''),
        'PORT': os.environ.get('DB_PORT', ''),
    }
}


# -------------------------------------------------------------------
# Password validation
# -------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# -------------------------------------------------------------------
# Internationalization / Time
# -------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'

# Match your deployment timezone (Philippines).
TIME_ZONE = 'Asia/Manila'

USE_I18N = True

# Keep True so Django stores datetimes as aware UTC internally.
USE_TZ = True


# -------------------------------------------------------------------
# Static files
# -------------------------------------------------------------------

# URL browsers will use
STATIC_URL = "/static/"

# Where your source static assets live during dev (CSS/JS/img under ./assets)
STATICFILES_DIRS = [BASE_DIR / "assets"]

# Where `collectstatic` will dump for prod serving (e.g. by WhiteNoise / nginx)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Optional: help WhiteNoise set long cache headers on hashed files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# -------------------------------------------------------------------
# Primary key field
# -------------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# -------------------------------------------------------------------
# Email / SMTP
# -------------------------------------------------------------------

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = True  # Gmail STARTTLS on 587

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'admin0108@gmail.com')

# IMPORTANT:
# Never hardcode this. Use an App Password (Gmail) or SMTP password from env.
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'webmaster@localhost')
